from conditions import *

bm_priority = [{'id':'Bestial Wrath',
                'conditions':[BestialWrathCondition,],
                'spell':BestialWrath},
               {'id':'Arcane Torrent',
                'conditions':[ArcaneTorrentCondition,],
                'spell':ArcaneTorrent},
               {'id':'Berserking',
                'conditions':[BerserkingCondition,],
                'spell':Berserking},
               {'id':'Kill Command',
                'conditions':[KillCommandCondition,],
                'spell':KillCommand},
               {'id':'Focus Fire',
                'conditions':[FocusFireCondition,],
                'spell':FocusFire},
               {'id':'Glaive Toss',
                'conditions':[GlaiveTossCondition,],
                'spell':GlaiveToss},
               {'id':'Powershot',
                'conditions':[PowershotCondition,],
                'spell':Powershot},
               {'id':'Barrage',
                'conditions':[BarrageCondition,],
                'spell':Barrage},
               {'id':'Dire Beast',
                'conditions':[DireBeastCondition,],
                'spell':DireBeast},
               {'id':'Fervor',
                'conditions':[FervorCondition,],
                'spell':Fervor},
               {'id':'A Murder of Crows',
                'conditions':[AMurderOfCrowsCondition,],
                'spell':MurderOfCrows},
               {'id':'Stampede',
                'conditions':[StampedeCondition,],
                'spell':Stampede},
               {'id':'Kill Shot',
                'conditions':[KillShotCondition,],
                'spell':KillShot},
               {'id':'Arcane Shot',
                'conditions':[ArcaneShotCondition,],
                'spell':ArcaneShot},
               {'id':'Focusing Shot',
                'conditions':[FocusingShotCondition,],
                'spell':FocusingShot},
               {'id':'Cobra Shot',
                'conditions':[CobraShotCondition,],
                'spell':CobraShot},
               {'id':'Pass',
                'conditions':[NoActionCondition,],
                'spell':NoneSpell},
              ]

mm_priority = [{'id':'Rapid Fire',
                'conditions':[RapidFireCondition,],
                'spell':RapidFire},
               {'id':'Arcane Torrent',
                'conditions':[ArcaneTorrentCondition,],
                'spell':ArcaneTorrent},
               {'id':'Berserking',
                'conditions':[BerserkingCondition,],
                'spell':Berserking},
               {'id':'Chimera Shot',
                'conditions':[ChimeraShotCondition,],
                'spell':ChimeraShot},
               {'id':'Glaive Toss',
                'conditions':[GlaiveTossCondition,],
                'spell':GlaiveToss},
               {'id':'Powershot',
                'conditions':[PowershotCondition,],
                'spell':Powershot},
               {'id':'Barrage',
                'conditions':[BarrageCondition,],
                'spell':Barrage},
               {'id':'Dire Beast',
                'conditions':[DireBeastCondition,],
                'spell':DireBeast},
               {'id':'Fervor',
                'conditions':[FervorCondition,],
                'spell':Fervor},
               {'id':'A Murder of Crows',
                'conditions':[AMurderOfCrowsCondition,],
                'spell':MurderOfCrows},
               {'id':'Stampede',
                'conditions':[StampedeCondition,],
                'spell':Stampede},
               {'id':'Kill Shot',
                'conditions':[KillShotCondition,],
                'spell':KillShot},
               {'id':'Aimed Shot',
                'conditions':[AimedShotCondition,],
                'spell':AimedShot},
               {'id':'Focusing Shot',
                'conditions':[FocusingShotCondition,],
                'spell':FocusingShot},
               {'id':'Steady Shot',
                'conditions':[SteadyShotCondition,],
                'spell':SteadyShot},
               {'id':'Pass',
                'conditions':[NoActionCondition,],
                'spell':NoneSpell},
              ]

sv_priority = [{'id':'Explosive Shot',
                'conditions':[ExplosiveShotCondition,],
                'spell':ExplosiveShot},
               {'id':'Arcane Torrent',
                'conditions':[ArcaneTorrentCondition,],
                'spell':ArcaneTorrent},
               {'id':'Berserking',
                'conditions':[BerserkingCondition,],
                'spell':Berserking},
               {'id':'Black Arrow',
                'conditions':[BlackArrowCondition,],
                'spell':BlackArrow},
               {'id':'Glaive Toss',
                'conditions':[GlaiveTossCondition,],
                'spell':GlaiveToss},
               {'id':'Powershot',
                'conditions':[PowershotCondition,],
                'spell':Powershot},
               {'id':'Barrage',
                'conditions':[BarrageCondition,],
                'spell':Barrage},
               {'id':'Dire Beast',
                'conditions':[DireBeastCondition,],
                'spell':DireBeast},
               {'id':'Fervor',
                'conditions':[FervorCondition,],
                'spell':Fervor},
               {'id':'A Murder of Crows',
                'conditions':[AMurderOfCrowsCondition,],
                'spell':MurderOfCrows},
               {'id':'Stampede',
                'conditions':[StampedeCondition,],
                'spell':Stampede},
               {'id':'Arcane Shot',
                'conditions':[ArcaneShotCondition,],
                'spell':ArcaneShot},
               {'id':'Focusing Shot',
                'conditions':[FocusingShotCondition,],
                'spell':FocusingShot},
               {'id':'Cobra Shot',
                'conditions':[CobraShotCondition,],
                'spell':CobraShot},
               {'id':'Pass',
                'conditions':[NoActionCondition,],
                'spell':NoneSpell},
              ]