from conditions import *

bm_priority = [{'id':'Focus Fire',
                'conditions':[FocusFireSpecialCondition,], # use at non max stacks
                'spell':FocusFire},
               {'id':'Bestial Wrath',
                'conditions':[BestialWrathCondition,BWHoldCondition],
                'spell':BestialWrath},
               {'id':'Focus Fire',
                'conditions':[FocusFireSpecialCondition,],
                'spell':FocusFire},
               {'id':'Arcane Torrent',
                'conditions':[ArcaneTorrentCondition,],
                'spell':ArcaneTorrent},
               {'id':'Berserking',
                'conditions':[BerserkingCondition,],
                'spell':Berserking},
               {'id':'Kill Command',
                'conditions':[KillCommandCondition,],
                'spell':KillCommand},
               {'id':'Focus Fire',
                'conditions':[FocusFireCondition,NoFFBWCondition],
                'spell':FocusFire},
               {'id':'Glaive Toss',
                'conditions':[GlaiveTossCondition,],
                'spell':GlaiveToss},
               {'id':'Powershot',
                'conditions':[PowershotCondition,],
                'spell':Powershot},
               {'id':'Barrage',
                'conditions':[BarrageCondition,],
                'spell':Barrage},
               {'id':'Dire Beast',
                'conditions':[DireBeastCondition,NoDBBWCondition],
                'spell':DireBeast},
               #{'id':'Fervor',
#                'conditions':[FervorCondition,],
#                'spell':Fervor},
               {'id':'A Murder of Crows',
                'conditions':[AMurderOfCrowsCondition,],
                'spell':MurderOfCrows},
               {'id':'Stampede',
                'conditions':[StampedeCondition,],
                'spell':Stampede},
               {'id':'Kill Shot',
                'conditions':[KillShotCondition,],
                'spell':KillShot},
               {'id':'Arcane Shot',
                'conditions':[ArcaneShotCondition,BMArcaneSpecialCondition,],
                'spell':ArcaneShot},
               {'id':'Focusing Shot',
                'conditions':[FocusingShotCondition,],
                'spell':FocusingShot},
               {'id':'Cobra Shot',
                'conditions':[CobraShotCondition,],
                'spell':CobraShot},
               {'id':'Pass',
                'conditions':[NoActionCondition,],
                'spell':NoneSpell},
              ]

mm_priority = [{'id':'Rapid Fire',
                'conditions':[RapidFireCondition,],
                'spell':RapidFire},
               {'id':'Arcane Torrent',
                'conditions':[ArcaneTorrentCondition,],
                'spell':ArcaneTorrent},
               {'id':'Berserking',
                'conditions':[BerserkingCondition,],
                'spell':Berserking},
               {'id':'Chimera Shot',
                'conditions':[ChimeraShotCondition,NoChimeraCACondition,AimedShotOnlyCACondition],
                'spell':ChimeraShot},
               {'id':'Glaive Toss',
                'conditions':[GlaiveTossCondition,AimedShotOnlyCACondition],
                'spell':GlaiveToss},
               {'id':'Powershot',
                'conditions':[PowershotCondition,AimedShotOnlyCACondition],
                'spell':Powershot},
               {'id':'Barrage',
                'conditions':[BarrageCondition,AimedShotOnlyCACondition],
                'spell':Barrage},
               {'id':'Dire Beast',
                'conditions':[DireBeastCondition,],
                'spell':DireBeast},
               #{'id':'Fervor',
#                'conditions':[FervorCondition,],
#                'spell':Fervor},
               {'id':'A Murder of Crows',
                'conditions':[AMurderOfCrowsCondition,AimedShotOnlyCACondition],
                'spell':MurderOfCrows},
               {'id':'Stampede',
                'conditions':[StampedeCondition,AimedShotOnlyCACondition],
                'spell':Stampede},
               {'id':'Kill Shot',
                'conditions':[KillShotCondition,],
                'spell':KillShot},
               {'id':'Aimed Shot',
                'conditions':[AimedShotCondition,MMAimedSpecialCondition],
                'spell':AimedShot},
               {'id':'Focusing Shot',
                'conditions':[FocusingShotCondition,],
                'spell':FocusingShot},
               {'id':'Steady Shot',
                'conditions':[SteadyShotCondition,],
                'spell':SteadyShot},
               {'id':'Pass',
                'conditions':[NoActionCondition,],
                'spell':NoneSpell},
              ]

sv_priority = [{'id':'Explosive Shot',
                'conditions':[ExplosiveShotCondition,],
                'spell':ExplosiveShot},
               {'id':'Arcane Torrent',
                'conditions':[ArcaneTorrentCondition,],
                'spell':ArcaneTorrent},
               {'id':'Berserking',
                'conditions':[BerserkingCondition,],
                'spell':Berserking},
               {'id':'Black Arrow',
                'conditions':[BlackArrowCondition,],
                'spell':BlackArrow},
               {'id':'Glaive Toss',
                'conditions':[GlaiveTossCondition,],
                'spell':GlaiveToss},
               {'id':'Powershot',
                'conditions':[PowershotCondition,],
                'spell':Powershot},
               {'id':'Barrage',
                'conditions':[BarrageCondition,],
                'spell':Barrage},
               {'id':'Dire Beast',
                'conditions':[DireBeastCondition,],
                'spell':DireBeast},
               #{'id':'Fervor',
#                'conditions':[FervorCondition,],
#                'spell':Fervor},
               {'id':'A Murder of Crows',
                'conditions':[AMurderOfCrowsCondition,],
                'spell':MurderOfCrows},
               {'id':'Stampede',
                'conditions':[StampedeCondition,],
                'spell':Stampede},
               {'id':'Arcane Shot',
                'conditions':[ArcaneShotCondition,SVArcaneSpecialCondition],
                'spell':ArcaneShot},
               {'id':'Focusing Shot',
                'conditions':[FocusingShotCondition,],
                'spell':FocusingShot},
               {'id':'Cobra Shot',
                'conditions':[CobraShotCondition,],
                'spell':CobraShot},
               {'id':'Pass',
                'conditions':[NoActionCondition,],
                'spell':NoneSpell},
              ]
              
              
              
              

bm_aoe_priority = [{'id':'Bestial Wrath',
                'conditions':[BestialWrathCondition,],
                'spell':BestialWrath},
               {'id':'Arcane Torrent',
                'conditions':[ArcaneTorrentCondition,],
                'spell':ArcaneTorrent},
               {'id':'Berserking',
                'conditions':[BerserkingCondition,],
                'spell':Berserking},
               {'id':'Multi-Shot',
                'conditions':[MultiShotCondition,BeastCleaveCondition],
                'spell':MultiShot},
               {'id':'Kill Command',
                'conditions':[KillCommandCondition,AoEMainNukesCondition,AoEMainNukesFocusCondition],
                'spell':KillCommand},
               {'id':'Focus Fire',
                'conditions':[FocusFireCondition,NoFFBWCondition],
                'spell':FocusFire},
               {'id':'Glaive Toss',
                'conditions':[GlaiveTossCondition,],
                'spell':GlaiveToss},
               {'id':'Powershot',
                'conditions':[PowershotCondition,],
                'spell':Powershot},
               {'id':'Barrage',
                'conditions':[BarrageCondition,],
                'spell':Barrage},
               {'id':'Dire Beast',
                'conditions':[DireBeastCondition,NoDBBWCondition,],
                'spell':DireBeast},
               #{'id':'Fervor',
#                'conditions':[FervorCondition,],
#                'spell':Fervor},
               {'id':'A Murder of Crows',
                'conditions':[AMurderOfCrowsCondition,AoEMainNukesCondition,AoEMainNukesFocusCondition],
                'spell':MurderOfCrows},
               {'id':'Stampede',
                'conditions':[StampedeCondition,AoEMainNukesCondition,AoEMainNukesFocusCondition],
                'spell':Stampede},
               {'id':'Kill Shot',
                'conditions':[KillShotCondition,],
                'spell':KillShot},
               {'id':'Explosive Trap',
                'conditions':[ExplosiveTrapCondition,],
                'spell':ExplosiveTrap},
               {'id':'Multi-Shot',
                'conditions':[MultiShotCondition,],
                'spell':MultiShot},
               {'id':'Focusing Shot',
                'conditions':[FocusingShotCondition,],
                'spell':FocusingShot},
               {'id':'Cobra Shot',
                'conditions':[CobraShotCondition,],
                'spell':CobraShot},
               {'id':'Pass',
                'conditions':[NoActionCondition,],
                'spell':NoneSpell},
              ]

mm_aoe_priority = [{'id':'Rapid Fire',
                'conditions':[RapidFireCondition,],
                'spell':RapidFire},
               {'id':'Arcane Torrent',
                'conditions':[ArcaneTorrentCondition,],
                'spell':ArcaneTorrent},
               {'id':'Berserking',
                'conditions':[BerserkingCondition,],
                'spell':Berserking},
               {'id':'Multi-Shot',
                'conditions':[MultiShotCondition,BombardmentCondition],
                'spell':MultiShot},
               {'id':'Chimera Shot',
                'conditions':[ChimeraShotCondition,],
                'spell':ChimeraShot},
               {'id':'Glaive Toss',
                'conditions':[GlaiveTossCondition,],
                'spell':GlaiveToss},
               {'id':'Powershot',
                'conditions':[PowershotCondition,],
                'spell':Powershot},
               {'id':'Barrage',
                'conditions':[BarrageCondition,],
                'spell':Barrage},
               {'id':'Dire Beast',
                'conditions':[DireBeastCondition,AoEMainNukesCondition,AoEMainNukesFocusCondition],
                'spell':DireBeast},
               #{'id':'Fervor',
#                'conditions':[FervorCondition,],
#                'spell':Fervor},
               {'id':'A Murder of Crows',
                'conditions':[AMurderOfCrowsCondition,AoEMainNukesCondition,AoEMainNukesFocusCondition],
                'spell':MurderOfCrows},
               {'id':'Stampede',
                'conditions':[StampedeCondition,],
                'spell':Stampede},
               {'id':'Kill Shot',
                'conditions':[KillShotCondition,AoEMainNukesCondition,AoEMainNukesFocusCondition],
                'spell':KillShot},
               {'id':'Explosive Trap',
                'conditions':[ExplosiveTrapCondition,],
                'spell':ExplosiveTrap},
               {'id':'Multi-Shot',
                'conditions':[MultiShotCondition,],
                'spell':MultiShot},
               {'id':'Focusing Shot',
                'conditions':[FocusingShotCondition,],
                'spell':FocusingShot},
               {'id':'Steady Shot',
                'conditions':[SteadyShotCondition,],
                'spell':SteadyShot},
               {'id':'Pass',
                'conditions':[NoActionCondition,],
                'spell':NoneSpell},
              ]

sv_aoe_priority = [{'id':'Explosive Shot',
                'conditions':[ExplosiveShotCondition,AoEMainNukesCondition,AoEMainNukesFocusCondition],
                'spell':ExplosiveShot},
               {'id':'Arcane Torrent',
                'conditions':[ArcaneTorrentCondition,],
                'spell':ArcaneTorrent},
               {'id':'Berserking',
                'conditions':[BerserkingCondition,],
                'spell':Berserking},
               {'id':'Glaive Toss',
                'conditions':[GlaiveTossCondition,],
                'spell':GlaiveToss},
               {'id':'Powershot',
                'conditions':[PowershotCondition,],
                'spell':Powershot},
               {'id':'Barrage',
                'conditions':[BarrageCondition,],
                'spell':Barrage},
               {'id':'Dire Beast',
                'conditions':[DireBeastCondition,AoEMainNukesCondition,AoEMainNukesFocusCondition],
                'spell':DireBeast},
               #{'id':'Fervor',
#                'conditions':[FervorCondition,],
#                'spell':Fervor},
               {'id':'A Murder of Crows',
                'conditions':[AMurderOfCrowsCondition,AoEMainNukesCondition,AoEMainNukesFocusCondition],
                'spell':MurderOfCrows},
               {'id':'Stampede',
                'conditions':[StampedeCondition,AoEMainNukesCondition,AoEMainNukesFocusCondition],
                'spell':Stampede},
               {'id':'Explosive Trap',
                'conditions':[ExplosiveTrapCondition,],
                'spell':ExplosiveTrap},
               {'id':'Multi-Shot',
                'conditions':[MultiShotCondition,],
                'spell':MultiShot},
               {'id':'Focusing Shot',
                'conditions':[FocusingShotCondition,],
                'spell':FocusingShot},
               {'id':'Cobra Shot',
                'conditions':[CobraShotCondition,],
                'spell':CobraShot},
               {'id':'Pass',
                'conditions':[NoActionCondition,],
                'spell':NoneSpell},
              ]